### ISSUE TITLE
`TypeError: Cannot read property 'create' of undefined`

### ISSUE THREAD

**Issue by marclundgren** [emberjs/ember-mocha#138]
Hello,

I tried running the provided basic acceptance test example:

```js
import Ember from 'ember'
import { describe, it } from 'mocha'
import { setupAcceptanceTest } from 'ember-mocha'
import { expect } from 'chai'

const Application = Ember.Application.extend({
  rootElement: '#ember-testing',
})

describe('basic acceptance test', function() {
  setupAcceptanceTest({ Application })

  it('can visit /', function() {
    visit('/')

    return andThen(() => {
      expect(currentURL()).to.equal('/')
    })
  })
})
```

however, it fails on the beforeEach hook:
```
TypeError: Cannot read property 'create' of undefined
    at http://localhost:7357/assets/test-support.js:22254:36
    at Backburner.run (http://localhost:7357/assets/vendor.js:10238:25)
    at Object.run (http://localhost:7357/assets/vendor.js:30220:27)
    at _default.createApplication (http://localhost:7357/assets/test-support.js:22253:27)
    at _default.setupContext (http://localhost:7357/assets/test-support.js:22233:110)
    at http://localhost:7357/assets/test-support.js:21924:28
    at Object.initializePromise (http://localhost:7357/assets/vendor.js:62561:7)
    at new Promise (http://localhost:7357/assets/vendor.js:64411:21)
    at nextStep (http://localhost:7357/assets/test-support.js:21923:20)
    at _default.invokeSteps (http://localhost:7357/assets/test-support.js:21930:16)
```

Am I doing something wrong?

**Comment by Turbo87** [comment]
sounds like you're hitting the same issue as #131, correct?

**Comment by andela-vdugeri** [comment]
I'm currently experiencing the same issue. I followed the exact instructions in the README.

**Comment by Turbo87** [comment]
see https://github.com/emberjs/ember-mocha/issues/131#issuecomment-275906648

**Comment by BL4CKC1PH3R** [comment]
How to solve this?

#131 (comment) is useless.
