### ISSUE TITLE
How to test serializers?

### ISSUE THREAD

**Issue by aaronrenner** [emberjs/ember-mocha#34]
I'm having difficulties trying to test my custom serializer and I am looking for suggestions

app/serializer/company.js

``` js
import Ember from 'ember';
import DS from 'ember-data';

export default DS.ActiveModelSerializer.extend({
  normalize: function(type, hash, property){
    var json = Ember.merge(hash, {
      links: {
        reports: "reports"
      }
    });
    return this._super(type, json, property);
  }
});
```

tests/unit/serializers/company-test.js

``` js
/* jshint expr:true */
import { expect } from 'chai';
import {
  describeModule,
  it
} from 'ember-mocha';

describeModule(
  'serializer:company',
  'CompanySerializer',
  {
    // Specify the other units that are required for this test.
    needs: ['model:company']
  },
  function() {
    describe('#normalize', function(){
      it('merges in a links hash', function(){
        var serializer = this.subject();

        var input = {
          id: 2,
          name: 'Acme Brick, Inc',
        };

        var Company = this.container.lookupFactory('model:company');

        var results = serializer.normalize(Company, input, 'company');

        expect(results.links).toEqual({
          reports: "reports"
        });
      });
    });
  }
);
```

This gives me the follow error

```
CompanySerializer #normalize merges in a links hash
    ✘ Cannot read property 'modelFor' of undefined
        TypeError: Cannot read property 'modelFor' of undefined
            at ember$data$lib$system$relationship$meta$$typeForRelationshipMeta (http://localhost:7357/assets/vendor.js:81655:21)
            at ember$data$lib$system$relationship$meta$$relationshipFromMeta (http://localhost:7357/assets/vendor.js:81667:15)
            at Function.<anonymous> (http://localhost:7357/assets/vendor.js:81742:30)
            at Function.ClassMixinProps.eachComputedProperty (http://localhost:7357/assets/vendor.js:43711:20)
            at Function.<anonymous> (http://localhost:7357/assets/vendor.js:81739:12)
            at Descriptor.ComputedPropertyPrototype.get (http://localhost:7357/assets/vendor.js:20246:25)
            at get (http://localhost:7357/assets/vendor.js:25733:21)
            at Function.ember$data$lib$system$model$model$$default.reopenClass.eachRelationship (http://localhost:7357/assets/vendor.js:82179:9)
            at ember$data$lib$serializers$rest_serializer$$default.extend.normalizeRelationships (http://localhost:7357/assets/vendor.js:73855:16)
            at ember$data$lib$serializers$json_serializer$$default.extend.normalize (http://localhost:7357/assets/vendor.js:73010:14)
```

I am thinking I might need to switch to using describeModel so that the store is loaded, but I ran into issues when I tried that too. I am on ember-mocha-0.6.2. Any suggestions would be greatly appreciated.

**Comment by efx** [comment]
FWIW, I copied ember-data's `setupStore` utility to recreate DS models appropriately. (https://github.com/emberjs/data/blob/master/tests/ember-configuration.js#L53)
The setup for the suite 
```javascript
		let env;
		beforeEach(function() {
				env = setupStore({
					serializer: serializer,
					adapter: DS.JSONAPIAdapter,
					user: User
				});
			});
			afterEach(function() {
				Ember.run(env.store, 'destroy');
			}); 
```
Then in a test I call: 
```
			it('errors when not given all arguments', function() {
				let payload = {portal_user_id: '1', first_name: 'Fred', last_name: 'Bob'};
				let mockUserClass = env.store.modelFor('user');
				expect(function() {
					serializer.normalizeResponse(payload, mockUserClass);
				}).to.throw();

			});
```
The `setupStore` utility makes it so that I can actually use the ember-data models and methods without having to  stub every method.

**Comment by Turbo87** [comment]
I hope that https://github.com/emberjs/data/blob/master/blueprints/serializer-test/mocha-files/tests/unit/__path__/__test__.js will give you some more answers. For everything else you should probably ask the `ember-data` team on how to best test a serializer since it's not specific to `ember-mocha`.
